// Generated from medieval FastAPI OpenAPI. Response defaults are always serialized.
export type Activity = { "id": string; "character_id": string; "kind": "training" | "study" | "travel"; "started_day": number; "processed_day": number; "decision_event_id": string; "skill": string | null; "progress_days": number; "origin_id": string | null; "destination_id": string | null; "route_id": string | null; "due_day": number | null; }
export type CalendarView = { "year": number; "month": number; "day": number; }
export type CargoParcel = { "id": string; "order_id": string; "quantity": number; "route_index": number; "stage": "waiting" | "traveling" | "unloading"; "due_day": number; "last_event_id": string | null; }
export type CausalLink = { "id": string; "event_id": string; "cause_event_id": string; "relation": CausalRelation; "weight": number; "note_key": string | null; "note_params": { [key: string]: unknown; } | null; "created_at": number; }
export type CausalOrigin = "deterministic" | "llm_interpretation" | "actor_decision" | "derived_condition" | "external_event"
export type CausalRelation = "triggered_by" | "enabled_by" | "motivated_by" | "response_to" | "resolves" | "prevented_by" | "contributed_to"
export type CausalView = { "event": WorldEvent; "causes": Array<WorldEvent>; "effects": Array<WorldEvent>; "next_after": number; "has_more": boolean; }
export type CharacterView = { "id": string; "name": string; "people": "human" | "elf" | "dwarf" | "orc"; "birth_day": number; "location_id": string; "population_group_id": string | null; "skills": Skills; "personality": Personality; "motivations": Array<string>; "titles": Array<string>; "death_day": number | null; "age_years": number; }
export type CreateRequest = { "seed"?: number; "character_count"?: number; "locale"?: "pt-BR"; "decision_policy"?: "routine-rules"; "replace"?: boolean; }
export type EconomyView = { "expansions": Array<ExpansionProject>; "expansion_blueprints": Array<ExpansionBlueprint>; "resources": Array<Resource>; "recipes": Array<Recipe>; "stocks": Array<Stock>; "accounts": Array<MoneyAccount>; "facilities": Array<ProductionFacility>; "payrolls": Array<Payroll>; "needs": Array<SettlementNeeds>; "markets": Array<Market>; "pending_orders": Array<FreightOrder>; "completed_order_count": number; "parcels": Array<CargoParcel>; "route_flows": Array<RouteFlow>; }
export type EmptyRequest = {  }
export type EntityRef = { "kind": string; "id": string; }
export type Envelope_CausalView_ = { "ok": true; "data": CausalView; "revision": number; }
export type Envelope_EconomyView_ = { "ok": true; "data": EconomyView; "revision": number; }
export type Envelope_EventsView_ = { "ok": true; "data": EventsView; "revision": number; }
export type Envelope_MapView_ = { "ok": true; "data": MapView; "revision": number; }
export type Envelope_ObservatoryView_ = { "ok": true; "data": ObservatoryView; "revision": number; }
export type Envelope_OptionsView_ = { "ok": true; "data": OptionsView; "revision": number; }
export type Envelope_SocietyView_ = { "ok": true; "data": SocietyView; "revision": number; }
export type Envelope_StatusView_ = { "ok": true; "data": StatusView; "revision": number; }
export type Envelope_WorldView_ = { "ok": true; "data": WorldView; "revision": number; }
export type Envelope_list_SaveView__ = { "ok": true; "data": Array<SaveView>; "revision": number; }
export type ErrorView = { "code": string; "message": string; }
export type EventsView = { "items": Array<WorldEvent>; "next_after": number; "has_more": boolean; }
export type FactKind = "occurrence" | "state_transition" | "derived_condition" | "decision"
export type FreightOrder = { "id": string; "source_id": string; "destination_id": string; "resource_id": string; "quantity": number; "delivered_quantity": number; "owner_ref": EntityRef; "route_ids": Array<string>; "created_day": number; "priority": number; "decision_ids": Array<string>; "last_event_id": string | null; }
export type GeographyLayer = { "width": number; "height": number; "terrain_rows": Array<Array<TileType>>; "elevation_rows": Array<Array<number>>; "water_bodies": Array<WaterBody>; }
export type HTTPValidationError = { "detail": Array<ValidationError>; }
export type InfrastructureSite = { "id": string; "kind": string; "name": string; "cell_refs": Array<[number, number]>; "region_ids": Array<number>; "route_ids": Array<string>; "water_body_ids": Array<string>; "capability_ids": Array<string>; "owner_ref": EntityRef | null; "maintainer_ref": EntityRef | null; "integrity": number; "enabled": boolean; "last_event_id": string | null; }
export type LoadRequest = { "save_id": string; }
export type MapView = { "map_id": string; "name": string; "width": number; "height": number; "region_rows": Array<Array<number>>; "geography": GeographyLayer; "settlements": Array<SettlementView>; "routes": Array<RouteView>; "sites": Array<InfrastructureSite>; }
export type Market = { "id": string; "prices": Record<string, number>; "updated_day": number; "last_event_id": string | null; }
export type MedievalRunConfig = { "seed": number; "character_count": number; "locale": "pt-BR"; "decision_policy": "routine-rules"; }
export type MoneyAccount = { "id": string; "owner_ref": EntityRef; "balance": number; "last_event_id": string | null; }
export type AuthorityOffice = { "id": string; "institution_ref": EntityRef; "holder_ref": EntityRef; "scopes": Array<"trade" | "supply" | "taxation" | "research" | "diplomacy">; "starts_day": number; "ends_day": number | null; }
export type GovernanceView = { "offices": Array<AuthorityOffice>; "tax_policies": Array<TaxPolicy>; "reports": Array<KnowledgeReport>; "objectives": Array<ObjectiveView>; "plans": Array<StrategicPlan>; }
export type TaxPolicy = { "id": string; "account_id": string; "income_rate": number; "last_event_id": string | null; }
export type Payroll = { "id": string; "day": number; "wage_per_worker": number; "workers_by_group": Record<string, number>; "gross": number; "tax": number; "last_event_id": string; }
export type KnowledgeReport = { "id": string; "recipient_ref": EntityRef; "publisher_ref": EntityRef; "stock_id": string; "resource_id": string; "kind": "inventory" | "offer"; "channel": "administrative_report" | "market_bulletin"; "observed_day": number; "quantity": number; "population": number; "unit_price": number; "quote_day": number; "event_id": string; }
export type ObjectiveView = { "id": string; "actor_ref": EntityRef; "settlement_id": string; "stock_id": string; "resource_id": string; "kind": "maintain_food_reserve" | "maintain_production_inputs"; "reserve_months": number; "motivation": string; "target_quantity": number; }
export type ObservatoryView = { "status": StatusView; "world": WorldView; "society": SocietyView; "economy": EconomyView; "map": MapView; "governance": GovernanceView; "research": ResearchView; }
export type StrategicPlan = { "id": string; "objective_id": string; "stage": "acquire" | "await_delivery" | "satisfied" | "blocked"; "order_ids": Array<string>; "blocker": string | null; "last_review_day": number; "last_event_id": string; }
export type OptionsView = { "defaults": MedievalRunConfig; "map_id": string; "map_name": string; "ai_available": boolean; }
export type Organization = { "id": string; "name": string; "kind": "noble_house" | "merchant_guild" | "arcane_tower" | "religious_order" | "cult"; "seat_id": string; "member_ids": Array<string>; "interests": Array<string>; }
export type Personality = { "ambition": number; "compassion": number; "loyalty": number; "caution": number; "curiosity": number; }
export type Polity = { "id": string; "name": string; "capital_id": string; "government": "crown" | "council" | "league"; "interests": Array<string>; }
export type PopulationGroup = { "id": string; "settlement_id": string; "people": "human" | "elf" | "dwarf" | "orc"; "occupation": "farmer" | "artisan" | "merchant" | "scholar" | "soldier" | "dependent"; "count": number; }
export type ProductionFacility = { "id": string; "site_id": string; "stock_id": string; "recipe_id": string; "max_batches": number; "payroll_account_id": string; "wage_per_worker": number; "last_batches": number; "last_limitations": Array<string>; "last_event_id": string | null; }
export type Recipe = { "id": string; "capability_id": string; "occupation": "farmer" | "artisan" | "merchant" | "scholar" | "soldier" | "dependent"; "workers": number; "inputs": Record<string, number>; "outputs": Record<string, number>; "required_technology_id": string | null; }
export type Resource = { "id": string; "name": string; "unit": string; "bulk": number; "base_price": number; }
export type Route = { "id": string; "endpoint_region_ids": [number, number]; "mode": string; "capacity": number; "quality": number; "enabled": boolean; "allowed_resource_ids": Array<string>; }
export type RouteFlow = { "id": string; "day": number; "bulk": number; }
export type RouteView = { "route": Route; "operational_capacity": number; }
export type SaveRequest = { "save_id": string; "overwrite"?: boolean; }
export type SaveView = { "save_id": string; "size_bytes": number; "modified_at": string; "compatible": boolean; "day": number | null; }
export type SettlementNeeds = { "id": string; "stock_id": string; "health": number; "unrest": number; "missing_food": number; "last_event_id": string | null; }
export type SettlementView = { "id": string; "region_id": number; "name": string; "kind": "city" | "village"; "administrator_id": string | null; "occupier_id": string | null; "claimant_ids": Array<string>; "housing_capacity": number; "population": number; "center": [number, number]; "health": number; "unrest": number; "missing_food": number; }
export type Skills = { "combat": number; "command": number; "diplomacy": number; "commerce": number; "investigation": number; "craftsmanship": number; "elemental_magic": number; "protection_magic": number; "restoration_magic": number; "evocation_magic": number; }
export type SocietyView = { "characters": Array<CharacterView>; "settlements": Array<SettlementView>; "polities": Array<Polity>; "organizations": Array<Organization>; "population_groups": Array<PopulationGroup>; "activities": Array<Activity>; }
export type SpeedRequest = { "jumps_per_second": number; }
export type StateDelta = { "id": string; "event_id": string; "owner_kind": string; "owner_id": string; "aspect": string; "before": string | null; "after": string | null; "magnitude": number | null; }
export type StatusView = { "product": "medieval-world-simulator"; "ready": boolean; "paused": boolean; "jumps_per_second": number; "day": number | null; "run_id": string | null; "last_error": ErrorView | null; }
export type Stock = { "id": string; "owner_ref": EntityRef; "location_id": string; "capacity": number; "goods": Record<string, number>; "last_event_ids": Record<string, string>; }
export type TileType = "plain" | "water" | "sea" | "mountain" | "forest" | "city" | "desert" | "rainforest" | "glacier" | "snow_mountain" | "volcano" | "grassland" | "swamp" | "cave" | "ruin" | "farm" | "sect" | "island" | "bamboo" | "gobi" | "tundra" | "marsh"
export type ValidationError = { "loc": Array<string | number>; "msg": string; "type": string; "input": unknown; "ctx": {  }; }
export type WaterBody = { "id": string; "kind": WaterBodyKind; "cell_refs": Array<[number, number]>; "navigable": boolean; "region_id": number | null; "flow_direction": [number, number] | null; }
export type WaterBodyKind = "river" | "lake" | "sea"
export type WorldEvent = { "id": string; "day": number; "sequence": number; "event_type": string; "content": string; "fact_kind": FactKind; "causal_origin": CausalOrigin; "decision": { [key: string]: unknown; } | null; "deltas": Array<StateDelta>; "causal_links": Array<CausalLink>; }
export type WorldView = { "day": number; "calendar": CalendarView; "config": MedievalRunConfig; "population": number; "living_characters": number; "settlements": number; "polities": number; "organizations": number; "events": number; "next_scheduled_day": number | null; }
export type ExpansionBlueprint = { id: string; name: string; inputs: Record<string, number>; workers_per_unit: number; wage_per_worker: number; required_units: number; monthly_units: number; capacity_gain: number; required_technology_id: string | null; from_recipe_id: string | null; to_recipe_id: string | null; additional_recipe_id: string | null; new_capacity: number | null; }
export type ExpansionProject = { id: string; facility_id: string; blueprint_id: string; owner_ref: EntityRef; decision_event_id: string; started_day: number; completed_units: number; last_work_day: number | null; stage: 'waiting' | 'building' | 'blocked' | 'completed'; blocker: string | null; last_event_id: string; }
export type Technology = { id: string; name: string; field: string; prerequisites: string[]; capability_id: string; skill: string; min_skill: number; required_units: number; monthly_units: number; inputs: Record<string, number>; assistant_occupation: PopulationGroup['occupation']; assistants_per_unit: number; wage_per_worker: number; }
export type ResearchProject = { id: string; owner_ref: EntityRef; technology_id: string; site_id: string; stock_id: string; account_id: string; researcher_id: string; sponsor_decision_id: string; researcher_decision_id: string; started_day: number; completed_units: number; last_work_day: number | null; stage: 'waiting' | 'researching' | 'blocked' | 'completed' | 'superseded'; blocker: string | null; last_event_id: string; }
export type TechnicalKnowledge = { id: string; owner_ref: EntityRef; technology_id: string; learned_day: number; channel: 'research' | 'teaching'; event_id: string; }
export type ResearchView = { technologies: Technology[]; projects: ResearchProject[]; knowledge: TechnicalKnowledge[]; }
